<a href="https://colab.research.google.com/github/shashank3110/MySpace/blob/master/Finite_Diff_Gradient.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np


In [0]:
def initialise(d,n):
  J=np.empty((n,d))
  x=np.random.rand(n,1)
  epsilon=10**(-6)
  print(epsilon)
  return J,x,epsilon

In [0]:
def compute(d,n,func):
  
  J,x,epsilon=initialise(d,n)
  #print(x.shape)
  #print(x)
  #J=np.matrix(J)
  basis=np.eye(n)
  #val=np.empty((10,1))
  
  for i in range(n):
    
    e=basis[i]
    
    e=e.reshape(n,1)

    val=(func(np.add(x,epsilon*e))-func(np.add(x,(-1)*epsilon*e)))/(2*epsilon)
    #print(val.shape)
   
    J[i]=np.transpose(val)
  
  print(J)
  J=np.transpose(J)
  
  print(J)
  
  J=J.reshape(d,n)
  print(J)
  df=get_gradient(func,x)
  print(df.shape)
  #df=df.reshape(10,5)

  norm_val=np.linalg.norm((J-df),np.inf)
  
  threshold=10**(-4)
  
  if norm_val <  threshold:
    return True
  else:
    return False

In [0]:
#A=np.random.rand(m,n)
def function1(x):
  #print(x.shape)
  val=np.matmul(A,x)
 # print("shape of A=".format(val.shape))
  return val

def function2(x):
  xt=np.transpose(x)
  return np.matmul(xt,x)

def get_gradient(f,x):
  print(type(A))
  
  if f.__name__=='function1':
    return np.matrix.reshape(A,(10,5))
  
  elif f.__name__=='function2':
    xt=np.transpose(x)
    return 2*xt
  
  else :
    return 0

In [12]:
m=10
n=5
d=m

A=np.matrix(np.random.rand(m,n))
print("mat A")
print(type(A))
print(A.shape)



mat A
<class 'numpy.matrixlib.defmatrix.matrix'>
(10, 5)


In [13]:
compute(d,n,function1)

1e-06
[[0.06612346 0.78726661 0.00356659 0.24365105 0.11657786 0.33370282
  0.98798964 0.55346223 0.00238317 0.11535091]
 [0.4891189  0.79802822 0.61369785 0.23075206 0.23224981 0.75018996
  0.77895159 0.7828049  0.68753317 0.99987758]
 [0.41949626 0.44243645 0.53103234 0.74682822 0.65907388 0.85124023
  0.0476803  0.41469827 0.96054522 0.46862742]
 [0.47835345 0.42680657 0.34645348 0.74325949 0.13397028 0.2241798
  0.03572105 0.36973261 0.01220818 0.32318436]
 [0.14141712 0.06422597 0.84117192 0.48712418 0.98253248 0.54255502
  0.3569694  0.20219924 0.23523355 0.31309076]]
[[0.06612346 0.4891189  0.41949626 0.47835345 0.14141712]
 [0.78726661 0.79802822 0.44243645 0.42680657 0.06422597]
 [0.00356659 0.61369785 0.53103234 0.34645348 0.84117192]
 [0.24365105 0.23075206 0.74682822 0.74325949 0.48712418]
 [0.11657786 0.23224981 0.65907388 0.13397028 0.98253248]
 [0.33370282 0.75018996 0.85124023 0.2241798  0.54255502]
 [0.98798964 0.77895159 0.0476803  0.03572105 0.3569694 ]
 [0.55346223 

True

In [14]:
compute(d,n,function2)

1e-06
[[0.66946169 0.66946169 0.66946169 0.66946169 0.66946169 0.66946169
  0.66946169 0.66946169 0.66946169 0.66946169]
 [1.35997994 1.35997994 1.35997994 1.35997994 1.35997994 1.35997994
  1.35997994 1.35997994 1.35997994 1.35997994]
 [0.41706638 0.41706638 0.41706638 0.41706638 0.41706638 0.41706638
  0.41706638 0.41706638 0.41706638 0.41706638]
 [1.20769413 1.20769413 1.20769413 1.20769413 1.20769413 1.20769413
  1.20769413 1.20769413 1.20769413 1.20769413]
 [0.10227076 0.10227076 0.10227076 0.10227076 0.10227076 0.10227076
  0.10227076 0.10227076 0.10227076 0.10227076]]
[[0.66946169 1.35997994 0.41706638 1.20769413 0.10227076]
 [0.66946169 1.35997994 0.41706638 1.20769413 0.10227076]
 [0.66946169 1.35997994 0.41706638 1.20769413 0.10227076]
 [0.66946169 1.35997994 0.41706638 1.20769413 0.10227076]
 [0.66946169 1.35997994 0.41706638 1.20769413 0.10227076]
 [0.66946169 1.35997994 0.41706638 1.20769413 0.10227076]
 [0.66946169 1.35997994 0.41706638 1.20769413 0.10227076]
 [0.66946169

True