In [1]:
import numpy as np
import subprocess
c=10 # if we increase C for high dimensions it becomes very slow
n=2 # for higher dimensions also the algo is very efficient except C is not very large
#when n was set to 100 iterations the norm(gradient) for the gradients collapsed ie =0 which gave divide by zero error for delta
w=0.01
w1=1.2
w2=0.5
alpha=1
theta=0.001
delmax=np.inf

x=np.ones(n)#array([1,1])

print(type(x))
print("x at start",x)


<class 'numpy.ndarray'>
x at start [1. 1.]


In [2]:
#C=np.diag(C)
def compute_C(n,c):
    C=np.zeros([n,n])
    for i in range(n):
        C[i][i]=(pow(c,(i)/(n-1)))
    return C 

In [3]:
def fSq(x):
    
    C=compute_C(n,c)
    f=np.dot(np.transpose(x),C)
    fsq=np.dot(f,x)
    fsq
    return fsq

In [4]:
def fHole(x):
    fhole=1-np.exp(-fSq(x))
    return fhole

In [5]:
C=compute_C(n,c)
val=np.dot(np.transpose(C),x)+np.dot(C,x)
print(x)
C=compute_C(n,c)

def gradient(x):
    val=np.dot(np.transpose(C),x)+np.dot(C,x)
    dict={'fSq': val,'fHole':np.exp(-fSq(x))*val}
    return dict
    
    

[1. 1.]


In [6]:
np.transpose(np.exp(x))

array([2.71828183, 2.71828183])

In [7]:
dict=gradient(x)
print(dict['fSq'])


[ 2. 20.]


In [8]:
def compute_grad_descent(x1,func):
    grad=gradient(x1)
    grad=grad[func.__name__]
    #print(grad)
    delta=-(grad/np.linalg.norm(grad))
    #print(delta)
    alpha=1
    theta=10
    #print(w)
    i=0
    print(alpha*delta)
    print(np.dot(np.transpose(alpha*delta), alpha*delta))
    print(np.linalg.norm(alpha*delta))
    st=''
    with open('data2.dat','w') as file:
        while  np.linalg.norm(alpha*delta) <theta :
            #num iterations
            print(alpha)
            grad=gradient(x1)
            grad=grad[func.__name__]
            delta=-(grad/np.linalg.norm(grad))
            j=0
            while func(x1+alpha*delta) > func(x1) +(w*(np.dot(np.transpose(grad),alpha*delta))) :
                    #num func evaluations
                    alpha=w2*alpha
                    j=j+1
            print("num evaluations",j)
            for val in x1:
                
                st=st+str(val)+" "

                
            st=st+str(func(x1))+" "
            st=st+'\n'
            
            file.write(st)
            x1=x1+alpha*delta
            
            alpha=min(w1*alpha,delmax)
            i=i+1
            if i==10:
                break
            
            st=''
    return x1,alpha,delta


In [9]:
# res=compute_grad_descent(x,fSq)
# print("Final Values")
# print("x",res[0])
# print("alpha",res[1])
# print("delta",res[2])

In [10]:
compute_grad_descent(x,fHole)

[-0.09950372 -0.99503719]
1.0
1.0
1
num evaluations 0
1.2
num evaluations 0
1.44
num evaluations 4
0.108
num evaluations 0
0.1296
num evaluations 1
0.07776
num evaluations 1
0.046655999999999996
num evaluations 0
0.055987199999999994
num evaluations 1
0.033592319999999995
num evaluations 0
0.040310783999999995
num evaluations 1


(array([-0.04257286, -0.00598309]),
 0.024186470399999997,
 array([ 0.36331375, -0.93166685]))

In [11]:
plot = subprocess.Popen(['gnuplot'], stdin=subprocess.PIPE)

In [12]:

plot.communicate(b'''

set isosamples 50, 50
set contour
#f(x,y) = x*x+10*y*y
f(x,y) = 1 - exp(-x*x-10*y*y)
splot [-1:1][-1:1] f(x,y)
pause 2
unset contour
splot [-3:3][-3:3] f(x,y), 'data2.dat' with lines lt rgb "#00FF00"
pause 50
''')

(None, None)